name: 'Prepare Dependencies'
description: 'Prepares all Node and pnpm dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install

